### ISSUE TITLE
Uncaught TypeError: Cannot read property 'togglePanel' of undefined

### ISSUE THREAD

**Issue by mmmpie** [wallabyjs/atom-wallaby#16]
[Enter steps to reproduce below:]

1. Open command panel
2. Type in 'wallaby'
3. Select 'toggle panel'

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'togglePanel' of undefined

```
At /Users/jon/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: Cannot read property 'togglePanel' of undefined
  at /Users/jon/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:2865
  at Function.e.value (/Users/jon/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:2973)
  at b.e.value (/Users/jon/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:2811)
  at atom-workspace._disposables.add.atom.commands.add.wallaby:toggle-panel (/Users/jon/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:1177)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -4:14.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:11.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:11.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:11.1.0 wallaby:start (atom-text-editor.editor)
  3x -1:03.7.0 core:close (div.settings-view.pane-item)
     -0:11.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:08.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 wallaby:toggle-panel (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
api-blueprint-preview, v0.6.0
atom-ctags, v4.3.0
atom-shortcuts, v0.0.2
atom-typescript, v7.1.4
atom-wallaby, v1.0.5
autocomplete-modules, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
bezier-curve-editor, v0.7.2
block-travel, v1.0.2
color-picker, v2.0.13
compare-files, v0.6.2
docblockr, v0.7.3
file-icons, v1.6.9
git-diff-details, v0.20.0
git-log, v0.4.1
git-tab-status, v1.9.2
hex, v0.6.2
highlight-selected, v0.10.1
hyperclick, v0.1.4
language-groovy, v0.4.0
linter, v1.8.1
linter-csslint, v1.0.7
linter-htmlhint, v0.1.1
linter-javac, v1.2.0
linter-js-yaml, v1.1.2
linter-jscs, v3.1.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-scss-lint, v2.2.1
linter-xmllint, v0.0.7
local-server-express, v0.3.1
minimap, v4.13.4
minimap-color-highlight, v4.1.4
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
nuclide-flow, v0.0.32
pretty-json, v0.4.1
regex-railroad-diagram, v0.10.3
test-status, v0.35.0
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by mmmpie** [comment]
I uninstalled wallaby and reinstalled it. When atom restarted wallaby updated itself to 1.0.9 and is working.

**Comment by ArtemGovorov** [comment]
Thanks for letting me know. I have fixed the issue so it shouldn't happen anymore in future.
