### ISSUE TITLE
Wallaby won't install

### ISSUE THREAD

**Issue by rantion** [wallabyjs/atom-wallaby#17]
module.js:340

    throw err;
          ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at cleanupDirs (/Users/Rachel/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/temp/lib/temp.js:96:20)
    at process.cleanup (/Users/Rachel/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/temp/lib/temp.js:119:19)
    at process.emit (events.js:95:17)
    at process.exit (node.js:740:17)
    at /Users/Rachel/Downloads/Atom.app/Contents/Resources/app/apm/lib/cli.js:13:22
    at options.callback (/Users/Rachel/Downloads/Atom.app/Contents/Resources/app/apm/lib/apm-cli.js:204:49)

**Comment by ArtemGovorov** [comment]
Interesting, we don't even use `rimraf`module and there's nothing from wallaby in the error stack, so I'm not sure what exactly could be causing the issue. 
What version of Atom are you using? Could you try updating to the latest Atom and try installing wallaby again please?
