### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

### ISSUE THREAD

**Issue by PavelAgejkin** [wallabyjs/atom-wallaby#21]
Just clicking around, while wallaby output full of failed tests

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.6

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

```
At C:\Users\Pavel\.atom\packages\atom-wallaby\wallaby-atom\index.js:14

Error: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
  at Error (native)
  at space-pen-div.<anonymous> (C:\Users\Pavel\.atom\packages\atom-wallaby\wallaby-atom\index.js:14:28127)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Pavel\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Pavel\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:11.6.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:11.3.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -1:09.9.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:09.6.0 core:cut (atom-text-editor.editor.is-focused)
  3x -1:08.7.0 core:delete (atom-text-editor.editor.is-focused)
  2x -1:05.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.8.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:save (atom-text-editor.editor.is-focused)
 24x -0:57.4.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:21.9.0 core:cut (atom-text-editor.editor.is-focused)
 16x -0:17.8.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:16.8.0 core:cut (atom-text-editor.editor.is-focused)
     -0:14.2.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:14 core:save (atom-text-editor.editor.is-focused)
  5x -0:02.8.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:00.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbol-gen"
    ],
    "ignoredNames": [
      ".meteor",
      ".git",
      "etc",
      "obj",
      "bin",
      "coverage",
      "node_modules",
      "packages"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.14
atom-wallaby, v1.0.6
atom-yeoman, v0.3.15
clipboard-plus, v0.5.1
code-links, v0.3.11
enhanced-tabs, v1.4.0
expand-region, v0.2.3
git-projects, v1.10.1
highlight-selected, v0.10.1
jshint, v1.8.1
json-schema, v0.1.15
language-cshtml, v0.1.1
last-cursor-position, v0.9.0
linter, v1.8.1
minimap, v4.13.4
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
omnisharp-atom, v0.25.2

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. Fixed in wallaby plugin 1.0.13.
