### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/atom-wallaby#23]
Trying `sudo apm install atom-wallaby`
Outputs:
```
> phantomjs@1.9.18 install /tmp/apm-install-dir-1151023-20130-100uw7u/node_modules/atom-wallaby/node_modules/phantomjs
> node install.js


npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-1151023-20130-100uw7u/node_modules/atom-wallaby/node_modules/phantomjs/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Linux 3.19.0-26-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/shamil/.atom/.apm/.apmrc" "--userconfig" "/home/shamil/.atom/.apmrc" "install" "/tmp/d-1151023-20130-69rhbf/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1151023-20130-100uw7u/npm-debug.log
```

-----------
`sudo npm i phantomjs` installs phantomjs@1.9.18 properly.

Ubuntu 14.04
node v5.1.0

**Comment by ArtemGovorov** [comment]
Thanks for the report. Seems like some issue with `phantomjs` package or the way `apm` works. As a workaround I may suggest installing the package directly from Atom editor (`Settings - Install`), it should work.

**Comment by StevenACoffman** [comment]
+1. I tried it from the Atom editor (Settings - Install) and got the same problem, but running:

```bash
apm install atom-wallaby
```
and it worked. 

node v5.3.0
atom v1.3.3
MacOS X v10.10.5
