### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/atom-wallaby#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.7

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.exports.fork (child_process.js:56:10)
    at EventEmitter._.extend.start (/Users/dave/.atom/packages/atom-wallaby/wallaby/client.js:14:806)
    at b.g.value (/Users/dave/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:10037)
    at HTMLButtonElement.wrapper (/Users/dave/.atom/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:2914:56)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:05.5.0 wallaby:toggle-panel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-javascript-semantic",
      "linter-scss-lint"
    ],
    "projectHome": "/Users/dave/Development",
    "themes": [
      "one-dark-ui",
      "duotone-dark-sea-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v2.1.2
aligner, v0.18.1
aligner-css, v1.2.0
aligner-scss, v1.1.0
atom-handlebars, v1.3.0
atom-ternjs, v0.13.2
atom-wallaby, v1.0.7
duotone-dark-sea-syntax, v1.0.0
editorconfig, v1.2.4
emmet, v2.4.1
language-SCSS, v0.4.0
language-babel, v2.15.3
linter, v1.11.3
linter-eslint, v6.0.0
linter-hlint, v0.4.2
linter-jscs, v3.4.4
react, v0.14.1
terminal-plus, v0.14.5
tool-bar, v0.2.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment]
Looks like an issue with spawning a node process. Was it a one-time issue or you can reliably reproduce it? If it's happening every time, try setting your full [node path in your Atom init script](http://wallabyjs.com/docs/intro/install.html#nodejs) for wallaby.

**Comment by davegomez** [comment]
It is happening all the time, but I'm gonna try the full path stuff and see how it goes.

**Comment by ArtemGovorov** [comment]
Did it start recently or never worked for you in Atom?
