### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addRightTile' of undefined

### ISSUE THREAD

**Issue by alexeden** [wallabyjs/atom-wallaby#34]
Steps to reproduce:

1. Cmd-Shift-P > Wallaby: Start 

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'addRightTile' of undefined

```
At /Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: Cannot read property 'addRightTile' of undefined
    at b.g.value (/Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14:5423)
    at /Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14:3240
    at pluginState.load (/Users/alexeden/enveq/share/atom/packages/atom-wallaby/lib/wallaby.js:46:11)
    at Function.e.value (/Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14:3130)
    at b.e.value (/Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14:2936)
    at atom-workspace._disposables.add.atom.commands.add.wallaby:start (/Users/alexeden/enveq/share/atom/packages/atom-wallaby/wallaby-atom/index.js:14:1300)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 wallaby:start (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-ternjs",
      "auto-reveal-in-sidebar",
      "atom-htmltidy",
      "linter-scss-lint",
      "api-workbench"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "bower_components",
      "dist",
      "webpack*stats.json"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "remote-sync",
      "atom-htmltidy",
      "terminal-plus"
    ],
    "projectHome": "/home/alexander",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
atom-wallaby, v1.0.7
autocomplete-paths, v1.0.2
editorconfig, v1.3.0
file-icons, v1.7.4
indent-guide-improved, v1.4.5
indentation-indicator, v0.6.0
language-arduino, v0.4.1
language-elm, v1.3.3
language-svg, v0.9.0
linter, v1.11.4
linter-elm-make, v0.4.0
linter-eslint, v7.2.0
linter-jade, v0.3.2
linter-jsonlint, v1.2.4
markdown-themeable-pdf, v1.0.1
minimap, v4.22.1
pigments, v0.26.0
pretty-json, v1.0.3
raml, v0.2.0
resize-indent, v0.2.1
svn, v0.0.9
terminal-plus, v0.14.5
tree-view-breadcrumb, v0.8.1

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the update will be installed automatically within the next few minutes (after your next wallaby.js (re)start). To force the update to be applied ASAP: 
- close Atom, 
- open your `user/.atom/packages/atom-wallaby/` folder, 
- delete `wallaby-atom` subfolder there,
- start Atom.
