### ISSUE TITLE
Uncaught TypeError: a(...) is not a function

### ISSUE THREAD

**Issue by MatthewThornton** [wallabyjs/atom-wallaby#40]
[Enter steps to reproduce below:]

1. Command-Shift-Space.  Tried to start Wallaby in Atom. This Wallaby installation has worked very well for months. 

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.8

### Stack Trace

Uncaught TypeError: a(...) is not a function

```
At /Users/matthewthornton/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: a(...) is not a function
    at /Users/matthewthornton/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:3187
    at pluginState.load (/Users/matthewthornton/.atom/packages/atom-wallaby/lib/wallaby.js:51:11)
    at Function.e.value (/Users/matthewthornton/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:3130)
    at b.e.value (/Users/matthewthornton/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:2936)
    at atom-workspace._disposables.add.atom.commands.add.wallaby:show-command-palette (/Users/matthewthornton/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:1106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:53.8.0 editor:indent (atom-text-editor.editor.power-mode.is-focused)
  3x -4:49.4.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  2x -4:16.4.0 linter:lint (atom-text-editor.editor.power-mode)
     -4:09.7.0 core:close (atom-text-editor.editor.power-mode.is-focused)
     -4:09.3.0 linter:lint (atom-text-editor.editor.power-mode.is-focused)
     -4:02.0 core:save (atom-text-editor.editor.power-mode.is-focused)
  2x -4:01.9.0 linter:lint (atom-text-editor.editor.power-mode.is-focused)
     -4:01.3.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -4:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:00.0 typescript:sync (atom-text-editor.editor.power-mode)
     -3:57.9.0 linter:lint (atom-text-editor.editor.power-mode.is-focused)
     -3:44.2.0 wallaby:show-command-palette (atom-text-editor.editor.power-mode.is-focused)
     -3:40.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
  2x -1:21.7.0 core:close (div.markdown-preview.native-key-bindings)
  4x -0:37.4.0 linter:lint (atom-text-editor.editor.power-mode.is-focused)
     -0:00.8.0 wallaby:show-command-palette (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons"
    ],
    "packagesWithKeymapsDisabled": [
      "ever-notedown"
    ],
    "themes": [
      "atom-dark-ui",
      "eclectic-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
atom-typescript, v9.0.0
atom-wallaby, v1.0.8
eclectic-syntax, v0.2.1
ever-notedown, v0.2.22
language-pug, v0.0.17
linter, v1.11.14
linter-pug-lint, v0.2.0
linter-tslint, v0.10.0

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment]
Just did a fresh install and can't reproduce the issue. Doe the editor restart help? Does it work if you use `Ctrl+1` to display wallaby panel? Traversing the stack, I can't yet see what could possibly go wrong, try re-installing the package and let me know if it helps.

**Comment by MatthewThornton** [comment]
Happy to report that an uninstall and reinstall worked. 
Probably Atom being dumb. Still love’n Wallaby

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
