### ISSUE TITLE
Uncaught TypeError: target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by eshikerya** [wallabyjs/atom-wallaby#61]
`CTRL+1` to open test panel causing the issue

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package 1.0.21

### Stack Trace

Uncaught TypeError: target[Symbol.iterator] is not a function

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/tooltip-manager.js:117

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/Applications/Atom Beta.app/Contents/Resources/app/src/tooltip-manager.js:117:35)
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:14:29383)
    at /packages/atom-wallaby/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/atom-wallaby/wallaby-atom/index.js:14:28671)
    at /packages/atom-wallaby/wallaby-atom/index.js:14:8294
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:14:8860)
    at /packages/atom-wallaby/wallaby-atom/index.js:14:2964
    at Function.value (/packages/atom-wallaby/wallaby-atom/index.js:14:3333)
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:14:2907)
    at /packages/atom-wallaby/wallaby-atom/index.js:14:1240)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:31.3.0 editor:duplicate-lines (input.hidden-input)
     -1:30.6.0 core:move-up (input.hidden-input)
     -1:30.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:29.4.0 core:move-down (input.hidden-input)
     -1:29.1.0 core:move-left (input.hidden-input)
     -1:29 datatip:toggle (input.hidden-input)
  3x -1:28.9.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:28.1.0 datatip:toggle (input.hidden-input)
  2x -1:27.9.0 core:backspace (input.hidden-input)
     -1:07.4.0 core:save (input.hidden-input)
  2x -0:47.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:46.4.0 core:select-down (input.hidden-input)
     -0:46 core:backspace (input.hidden-input)
  8x -0:44.7.0 core:move-down (input.hidden-input)
     -0:38.3.0 core:save (input.hidden-input)
  2x -0:34.5.0 wallaby:focus-panel (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
atom-import-sort 3.3.0 
atom-wallaby 1.0.21 
autocomplete-flow 1.6.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.8.0 
build-tools 4.5.12 
build-tools-ant 0.1.1 
change-case 0.6.5 
cobalt2-syntax 0.5.1 
docblockr 0.13.2 
file-icons 2.1.13 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-css 0.2.0 
ide-flowtype 0.17.4 
ide-json 0.1.0 
ide-yaml 0.4.1 
javascript-refactor 0.5.7 
js-hyperclick 1.12.1 
js-refactor 0.7.5 
language-babel 2.77.3 
language-generic-config 1.4.0 
language-js-specs 0.1.0 
language-soy 0.3.2 
linter 2.2.0 
pigments 0.40.2 
prettier-atom 0.40.0 
refactor 0.11.5 
Sublime-Style-Column-Selection 1.7.4 
tab-foldername-index 3.2.2 
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in 1.0.22.
