### ISSUE TITLE
Uncaught TypeError: a(...) is not a constructor

### ISSUE THREAD

**Issue by JBGoldberg** [wallabyjs/atom-wallaby#62]
[Enter steps to reproduce:]

1. [Shift] + [Command] + [P]
2. Find Wallaby: Start in dialog and choose it.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package 1.0.22

### Stack Trace

Uncaught TypeError: a(...) is not a constructor

```
At /Users/goldberg/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: a(...) is not a constructor
    at /packages/atom-wallaby/wallaby-atom/index.js:14:3460
    at pluginState.load (/packages/atom-wallaby/lib/wallaby.js:58:11)
    at Function.value (/packages/atom-wallaby/wallaby-atom/index.js:14:3403)
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:14:2972)
    at /packages/atom-wallaby/wallaby-atom/index.js:14:1300)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:10.2.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:07.7.0 core:move-down (input.hidden-input)
     -0:07.3.0 core:confirm (input.hidden-input)
     -0:07.3.0 wallaby:start (div.tool-panel.tree-view)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angular2-snippets 0.4.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-typescript 12.0.0 
atom-wallaby 1.0.22 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
deckard 0.2.11 
emmet 2.4.3 
intentions 1.1.5 
ionic-framework-snippets 1.2.1 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-ui-default 1.6.10 
nord-atom-syntax 0.9.1 
php-cs-fixer 4.1.1 
php-twig 4.0.0 
phpunit 1.2.0 
platformio-ide-terminal 2.8.0 
typescript-modules-helper 0.8.0 
```

**Comment by ArtemGovorov** [comment]
Unfortunately we can't reproduce the issue locally. Please try re-installing the package and if it doesn't help - try running Wallaby with other packages disabled to see if something else is affecting it.
