### ISSUE TITLE
Uncaught Error: Cannot find module 'q'

### ISSUE THREAD

**Issue by Gavin-YYC** [wallabyjs/atom-wallaby#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package 1.0.22

### Stack Trace

Uncaught Error: Cannot find module 'q'

```
At module.js:472

Error: Cannot find module 'q'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-wallaby/lib/wallaby.js:22:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-fecs 0.2.2 
atom-ide-ui 0.9.4 
atom-wallaby 1.0.22 
es6-javascript 1.0.0 
language-atomx 0.0.1 
language-vue 0.23.1 
monokai 0.24.0 
node-debugger 1.10.1 
platformio-ide-terminal 2.8.1 
teletype 0.10.0 
```

**Comment by ArtemGovorov** [comment]
Looks like your wallaby package installation is corrupted. Please try to re-install `atom-wallaby` package. If it doesn't help, please archive and attach your `/packages/atom-wallaby` folder.
